-- Enable pg_stat_statements for production query performance analysis.
-- Tracks execution count, total time, mean time, and min/max time per
-- normalized query. Query with:
--
--   SELECT query, calls, mean_exec_time, max_exec_time, total_exec_time
--   FROM pg_stat_statements
--   ORDER BY mean_exec_time DESC
--   LIMIT 20;
--
-- Requires pg_stat_statements in shared_preload_libraries (Railway default).
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
