FROM oven/bun:latest AS build
WORKDIR /app
COPY package.json bun.lock ./
COPY apps/api/package.json ./apps/api/
COPY packages/shared/package.json ./packages/shared/
RUN bun install
ARG COMMIT_SHA
COPY . .

FROM oven/bun:latest
WORKDIR /app
COPY --from=build /app ./
EXPOSE 3001
CMD ["bun", "--cwd", "apps/api", "src/index.ts"]
