import type { SlotDef } from './shared';
import { NC, ADV } from './shared';

function phulPower(exerciseId: string, sets: number, reps: number): SlotDef {
  return {
    id: exerciseId,
    exerciseId,
    tier: 'power',
    stages: [{ sets, reps }],
    onSuccess: { type: 'add_weight' },
    onMidStageFail: NC,
    onFinalStageFail: { type: 'deload_percent', percent: 10 },
    startWeightKey: exerciseId,
  };
}

function phulDP(
  exerciseId: string,
  sets: number,
  minReps: number,
  maxReps: number,
  inc: number,
  slotId?: string
): SlotDef {
  const id = slotId ?? exerciseId;
  const stages: { sets: number; reps: number }[] = [];
  for (let r = minReps; r <= maxReps; r++) {
    stages.push({ sets, reps: r });
  }
  return {
    id,
    exerciseId,
    tier: 'hypertrophy',
    stages,
    onSuccess: ADV,
    onFinalStageSuccess: { type: 'add_weight_reset_stage', amount: inc },
    onUndefined: ADV,
    onMidStageFail: NC,
    onFinalStageFail: NC,
    startWeightKey: id,
  };
}

export const PHUL_DEFINITION_JSONB = {
  cycleLength: 4,
  totalWorkouts: 80,
  workoutsPerWeek: 4,
  exercises: {
    bench: {},
    incline_db_press: {},
    bent_over_row: {},
    lat_pulldown: {},
    ohp: {},
    curl_bar: {},
    skullcrusher: {},
    squat: {},
    deadlift: {},
    prensa: {},
    curl_fem: {},
    standing_calf_raise: {},
    incline_bench: {},
    apert: {},
    seated_row: {},
    dbrow: {},
    lateral_raise: {},
    incline_curl: {},
    triceps_extension: {},
    front_squat: {},
    zancadas: {},
    ext_quad: {},
    gemelo_sent: {},
    leg_press_gem: {},
  },
  configFields: [
    // Fuerza Superior
    {
      key: 'bench',
      label: 'Press Banca',
      type: 'weight',
      min: 2.5,
      step: 2.5,
      group: 'Fuerza Superior',
    },
    {
      key: 'bent_over_row',
      label: 'Remo con Barra',
      type: 'weight',
      min: 2.5,
      step: 2.5,
      group: 'Fuerza Superior',
    },
    {
      key: 'ohp',
      label: 'Press Militar',
      type: 'weight',
      min: 2.5,
      step: 2.5,
      group: 'Fuerza Superior',
    },
    {
      key: 'incline_db_press',
      label: 'Press Inclinado Mancuernas',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Fuerza Superior',
    },
    {
      key: 'lat_pulldown',
      label: 'Jalón al Pecho',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Fuerza Superior',
    },
    {
      key: 'curl_bar',
      label: 'Curl con Barra',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Fuerza Superior',
    },
    {
      key: 'skullcrusher',
      label: 'Extensión de Tríceps Tumbado',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Fuerza Superior',
    },
    // Fuerza Inferior
    {
      key: 'squat',
      label: 'Sentadilla',
      type: 'weight',
      min: 2.5,
      step: 2.5,
      group: 'Fuerza Inferior',
    },
    {
      key: 'deadlift',
      label: 'Peso Muerto',
      type: 'weight',
      min: 2.5,
      step: 2.5,
      group: 'Fuerza Inferior',
    },
    { key: 'prensa', label: 'Prensa', type: 'weight', min: 0, step: 5, group: 'Fuerza Inferior' },
    {
      key: 'curl_fem_power',
      label: 'Curl Femoral (Fuerza)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Fuerza Inferior',
    },
    {
      key: 'standing_calf_raise',
      label: 'Gemelo de Pie',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Fuerza Inferior',
    },
    // Hipertrofia Superior
    {
      key: 'incline_bench',
      label: 'Press Inclinado Barra',
      type: 'weight',
      min: 2.5,
      step: 2.5,
      group: 'Hipertrofia Superior',
    },
    {
      key: 'apert',
      label: 'Aperturas',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Hipertrofia Superior',
    },
    {
      key: 'seated_row',
      label: 'Remo Sentado',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Hipertrofia Superior',
    },
    {
      key: 'dbrow',
      label: 'Remo Mancuernas',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Hipertrofia Superior',
    },
    {
      key: 'lateral_raise',
      label: 'Elevaciones Laterales',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Hipertrofia Superior',
    },
    {
      key: 'incline_curl',
      label: 'Curl Inclinado',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Hipertrofia Superior',
    },
    {
      key: 'triceps_extension',
      label: 'Extensión Tríceps',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Hipertrofia Superior',
    },
    // Hipertrofia Inferior
    {
      key: 'front_squat',
      label: 'Sentadilla Frontal',
      type: 'weight',
      min: 2.5,
      step: 2.5,
      group: 'Hipertrofia Inferior',
    },
    {
      key: 'zancadas',
      label: 'Zancadas',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Hipertrofia Inferior',
    },
    {
      key: 'ext_quad',
      label: 'Extensión Cuádriceps',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Hipertrofia Inferior',
    },
    {
      key: 'curl_fem_hyp',
      label: 'Curl Femoral (Hipertrofia)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Hipertrofia Inferior',
    },
    {
      key: 'gemelo_sent',
      label: 'Gemelo Sentado',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Hipertrofia Inferior',
    },
    {
      key: 'leg_press_gem',
      label: 'Prensa Gemelo',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Hipertrofia Inferior',
    },
  ],
  weightIncrements: {
    bench: 2.5,
    squat: 2.5,
    deadlift: 5,
    bent_over_row: 2.5,
  },
  days: [
    {
      name: 'Fuerza Superior',
      slots: [
        phulPower('bench', 4, 5),
        phulDP('incline_db_press', 3, 6, 10, 0.5),
        phulPower('bent_over_row', 4, 5),
        phulDP('lat_pulldown', 3, 6, 10, 2.5),
        phulDP('ohp', 3, 5, 8, 2.5),
        phulDP('curl_bar', 3, 6, 10, 2.5),
        phulDP('skullcrusher', 3, 6, 10, 2.5),
      ],
    },
    {
      name: 'Fuerza Inferior',
      slots: [
        phulPower('squat', 4, 5),
        phulPower('deadlift', 4, 5),
        phulDP('prensa', 4, 10, 15, 5),
        phulDP('curl_fem', 3, 6, 10, 2.5, 'curl_fem_power'),
        phulDP('standing_calf_raise', 4, 6, 10, 2.5),
      ],
    },
    {
      name: 'Hipertrofia Superior',
      slots: [
        phulDP('incline_bench', 4, 8, 12, 2.5),
        phulDP('apert', 3, 8, 12, 0.5),
        phulDP('seated_row', 4, 8, 12, 2.5),
        phulDP('dbrow', 3, 8, 12, 0.5),
        phulDP('lateral_raise', 3, 8, 12, 0.5),
        phulDP('incline_curl', 3, 8, 12, 0.5),
        phulDP('triceps_extension', 3, 8, 12, 2.5),
      ],
    },
    {
      name: 'Hipertrofia Inferior',
      slots: [
        phulDP('front_squat', 4, 8, 12, 2.5),
        phulDP('zancadas', 3, 8, 12, 2.5),
        phulDP('ext_quad', 3, 10, 15, 2.5),
        phulDP('curl_fem', 3, 10, 15, 2.5, 'curl_fem_hyp'),
        phulDP('gemelo_sent', 3, 8, 12, 2.5),
        phulDP('leg_press_gem', 3, 8, 12, 2.5),
      ],
    },
  ],
};
