import type { SlotDef } from './shared';
import { NC, ADV } from './shared';

function pplMainWork(exerciseId: string, slotId: string, tmKey: string): SlotDef {
  return {
    id: `${slotId}_work`,
    exerciseId,
    tier: 'main',
    role: 'secondary',
    trainingMaxKey: tmKey,
    tmPercent: 0.75,
    stages: [{ sets: 1, reps: 5 }],
    onSuccess: NC,
    onUndefined: NC,
    onMidStageFail: NC,
    onFinalStageFail: NC,
    startWeightKey: tmKey,
  };
}

function pplMainAmrap(exerciseId: string, slotId: string, tmKey: string, inc: number): SlotDef {
  return {
    id: `${slotId}_amrap`,
    exerciseId,
    tier: 'main',
    role: 'primary',
    trainingMaxKey: tmKey,
    tmPercent: 0.85,
    stages: [{ sets: 1, reps: 5, amrap: true }],
    onSuccess: { type: 'update_tm', amount: inc, minAmrapReps: 5 },
    onUndefined: NC,
    onMidStageFail: NC,
    onFinalStageFail: NC,
    startWeightKey: tmKey,
  };
}

function pplSecondary(
  exerciseId: string,
  slotId: string,
  tmKey: string,
  pct: number,
  sets: number,
  reps: number
): SlotDef {
  return {
    id: slotId,
    exerciseId,
    tier: 'secondary',
    role: 'secondary',
    trainingMaxKey: tmKey,
    tmPercent: pct,
    stages: [{ sets, reps }],
    onSuccess: NC,
    onUndefined: NC,
    onMidStageFail: NC,
    onFinalStageFail: NC,
    startWeightKey: tmKey,
  };
}

function pplDp810(exerciseId: string, inc: number, sets: number, slotId?: string): SlotDef {
  return {
    id: slotId ?? exerciseId,
    exerciseId,
    tier: 'accessory',
    role: 'accessory',
    stages: [
      { sets, reps: 8, repsMax: 10 },
      { sets, reps: 9, repsMax: 10 },
      { sets, reps: 10, repsMax: 10 },
    ],
    onSuccess: ADV,
    onFinalStageSuccess: { type: 'add_weight_reset_stage', amount: inc },
    onUndefined: ADV,
    onMidStageFail: NC,
    onFinalStageFail: NC,
    startWeightKey: slotId ?? exerciseId,
  };
}

function pplDp1520(exerciseId: string, inc: number, sets: number, slotId?: string): SlotDef {
  return {
    id: slotId ?? exerciseId,
    exerciseId,
    tier: 'accessory',
    role: 'accessory',
    stages: [
      { sets, reps: 15, repsMax: 20 },
      { sets, reps: 16, repsMax: 20 },
      { sets, reps: 17, repsMax: 20 },
      { sets, reps: 18, repsMax: 20 },
      { sets, reps: 19, repsMax: 20 },
      { sets, reps: 20, repsMax: 20 },
    ],
    onSuccess: ADV,
    onFinalStageSuccess: { type: 'add_weight_reset_stage', amount: inc },
    onUndefined: ADV,
    onMidStageFail: NC,
    onFinalStageFail: NC,
    startWeightKey: slotId ?? exerciseId,
  };
}

const PPL531_DAYS = [
  // Pull A
  {
    name: 'Pull A',
    slots: [
      pplMainWork('deadlift', 'deadlift_main', 'deadlift_tm'),
      pplMainAmrap('deadlift', 'deadlift_main', 'deadlift_tm', 5),
      pplDp810('lat_pulldown', 2.5, 3),
      pplDp810('seated_row', 2.5, 3),
      pplDp1520('face_pull', 2.5, 3),
      pplDp810('hammer_curl', 0.5, 3, 'hammer_curl_a'),
      pplDp810('incline_curl', 0.5, 3),
    ],
  },
  // Push A
  {
    name: 'Push A',
    slots: [
      pplMainWork('bench', 'bench_main', 'bench_tm'),
      pplMainAmrap('bench', 'bench_main', 'bench_tm', 2.5),
      pplSecondary('ohp', 'ohp_secondary', 'ohp_tm', 0.5, 3, 10),
      pplDp810('incline_db_press', 0.5, 3),
      pplDp810('triceps_pushdown', 2.5, 3),
      pplDp810('triceps_extension', 2.5, 3),
      pplDp1520('lateral_raise', 0.5, 3),
    ],
  },
  // Legs A
  {
    name: 'Legs A',
    slots: [
      pplMainWork('squat', 'squat_main', 'squat_tm'),
      pplMainAmrap('squat', 'squat_main', 'squat_tm', 5),
      pplDp810('barbell_rdl', 0.5, 3),
      pplDp810('bulgarian_split_squat', 0.5, 3),
      pplDp810('cable_pull_through', 2.5, 3),
      pplDp810('standing_calf_raise', 2.5, 5),
    ],
  },
  // Pull B
  {
    name: 'Pull B',
    slots: [
      pplMainWork('pullup', 'pullup_main', 'pullup_tm'),
      pplMainAmrap('pullup', 'pullup_main', 'pullup_tm', 2.5),
      pplDp810('bent_over_row', 0.5, 3),
      pplDp810('seated_row', 2.5, 3),
      pplDp1520('incline_row', 2.5, 5),
      pplDp810('hammer_curl', 0.5, 4, 'hammer_curl_b'),
      pplDp810('lying_bicep_curl', 0.5, 4),
    ],
  },
  // Push B
  {
    name: 'Push B',
    slots: [
      pplMainWork('ohp', 'ohp_main', 'ohp_tm'),
      pplMainAmrap('ohp', 'ohp_main', 'ohp_tm', 2.5),
      pplSecondary('bench', 'bench_secondary', 'bench_tm', 0.5, 3, 10),
      pplDp810('incline_db_press', 0.5, 3),
      pplDp810('triceps_pushdown', 2.5, 3),
      pplDp810('triceps_extension', 2.5, 3),
      pplDp1520('lateral_raise', 0.5, 3),
    ],
  },
  // Legs B
  {
    name: 'Legs B',
    slots: [
      pplSecondary('squat', 'squat_secondary', 'squat_tm', 0.6, 3, 8),
      pplDp810('dumbbell_rdl', 0.5, 3),
      pplDp810('bulgarian_split_squat', 0.5, 3),
      pplDp810('seated_leg_curl', 2.5, 3),
      pplDp810('standing_calf_raise', 2.5, 5),
    ],
  },
];

export const PPL531_DEFINITION_JSONB = {
  cycleLength: 6,
  totalWorkouts: 156,
  workoutsPerWeek: 6,
  exercises: {
    deadlift: {},
    bench: {},
    squat: {},
    pullup: {},
    ohp: {},
    lat_pulldown: {},
    seated_row: {},
    face_pull: {},
    hammer_curl: {},
    incline_curl: {},
    bent_over_row: {},
    incline_row: {},
    lying_bicep_curl: {},
    incline_db_press: {},
    triceps_pushdown: {},
    triceps_extension: {},
    lateral_raise: {},
    barbell_rdl: {},
    dumbbell_rdl: {},
    bulgarian_split_squat: {},
    cable_pull_through: {},
    standing_calf_raise: {},
    seated_leg_curl: {},
  },
  configFields: [
    {
      key: 'squat_tm',
      label: 'Sentadilla (Training Max)',
      type: 'weight',
      min: 10,
      step: 2.5,
      group: 'Training Max',
    },
    {
      key: 'bench_tm',
      label: 'Press Banca (Training Max)',
      type: 'weight',
      min: 10,
      step: 2.5,
      group: 'Training Max',
    },
    {
      key: 'deadlift_tm',
      label: 'Peso Muerto (Training Max)',
      type: 'weight',
      min: 10,
      step: 2.5,
      group: 'Training Max',
    },
    {
      key: 'ohp_tm',
      label: 'Press Militar (Training Max)',
      type: 'weight',
      min: 10,
      step: 2.5,
      group: 'Training Max',
    },
    {
      key: 'pullup_tm',
      label: 'Dominadas (Training Max)',
      type: 'weight',
      min: 10,
      step: 2.5,
      group: 'Training Max',
    },
    {
      key: 'lat_pulldown',
      label: 'Jalon al Pecho',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Accesorios Tiron',
    },
    {
      key: 'seated_row',
      label: 'Remo Sentado',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Accesorios Tiron',
    },
    {
      key: 'face_pull',
      label: 'Face Pull',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Accesorios Tiron',
    },
    {
      key: 'hammer_curl_a',
      label: 'Curl Martillo (Pull A)',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Tiron',
    },
    {
      key: 'incline_curl',
      label: 'Curl Inclinado',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Tiron',
    },
    {
      key: 'bent_over_row',
      label: 'Remo con Barra',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Tiron',
    },
    {
      key: 'incline_row',
      label: 'Remo Inclinado',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Accesorios Tiron',
    },
    {
      key: 'hammer_curl_b',
      label: 'Curl Martillo (Pull B)',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Tiron',
    },
    {
      key: 'lying_bicep_curl',
      label: 'Curl Tumbado',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Tiron',
    },
    {
      key: 'incline_db_press',
      label: 'Press Inclinado Mancuernas',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Empuje',
    },
    {
      key: 'triceps_pushdown',
      label: 'Extension Triceps Polea',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Accesorios Empuje',
    },
    {
      key: 'triceps_extension',
      label: 'Extension Triceps',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Accesorios Empuje',
    },
    {
      key: 'lateral_raise',
      label: 'Elevaciones Laterales',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Empuje',
    },
    {
      key: 'barbell_rdl',
      label: 'RDL con Barra',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Piernas',
    },
    {
      key: 'dumbbell_rdl',
      label: 'RDL con Mancuernas',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Piernas',
    },
    {
      key: 'bulgarian_split_squat',
      label: 'Zancada Bulgara',
      type: 'weight',
      min: 0,
      step: 0.5,
      group: 'Accesorios Piernas',
    },
    {
      key: 'cable_pull_through',
      label: 'Pull Through en Polea',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Accesorios Piernas',
    },
    {
      key: 'standing_calf_raise',
      label: 'Gemelo de Pie',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Accesorios Piernas',
    },
    {
      key: 'seated_leg_curl',
      label: 'Curl Femoral Sentado',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Accesorios Piernas',
    },
  ],
  weightIncrements: {
    lat_pulldown: 2.5,
    seated_row: 2.5,
    face_pull: 2.5,
    hammer_curl: 0.5,
    incline_curl: 0.5,
    bent_over_row: 0.5,
    incline_row: 2.5,
    lying_bicep_curl: 0.5,
    incline_db_press: 0.5,
    triceps_pushdown: 2.5,
    triceps_extension: 2.5,
    lateral_raise: 0.5,
    barbell_rdl: 0.5,
    dumbbell_rdl: 0.5,
    bulgarian_split_squat: 0.5,
    cable_pull_through: 2.5,
    standing_calf_raise: 2.5,
    seated_leg_curl: 2.5,
  },
  days: PPL531_DAYS,
};
